<a href="https://colab.research.google.com/github/ShubhamJadhav03/21-days-pytorch/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [102]:
import torch
torch.__version__

'2.9.0+cpu'

#Scalar

In [103]:
scalar = torch.tensor(7)

In [104]:
scalar

tensor(7)

In [105]:
scalar.ndim

0

In [106]:
scalar.item()

7

#Vector

In [107]:
vector = torch.tensor([7,7])

In [108]:
vector

tensor([7, 7])

In [109]:
vector.ndim

1

In [110]:
vector.shape

torch.Size([2])

#Matrix

In [111]:
MATRIX = torch.tensor([[1,2],
                       [3,4]
                       ])

In [112]:
MATRIX.ndim

2

In [113]:
MATRIX.shape

torch.Size([2, 2])

#Tensor

In [114]:
TENSOR = torch.tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [115]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [116]:
TENSOR.ndim

3

In [117]:
TENSOR.shape

torch.Size([1, 3, 3])

In [118]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [119]:
TENSOR[0,0]

tensor([1, 2, 3])

In [120]:
TENSOR[0,0,0]

tensor(1)

#Random tensors

In [121]:
random_tensor = torch.rand(size = (2,3,3))

In [122]:
random_tensor, random_tensor.dtype

(tensor([[[0.5457, 0.7303, 0.5268],
          [0.6694, 0.3213, 0.4008],
          [0.2892, 0.9977, 0.6649]],
 
         [[0.5646, 0.9323, 0.4621],
          [0.4027, 0.1680, 0.1170],
          [0.5063, 0.6061, 0.5141]]]),
 torch.float32)

In [123]:
random_tensor[1]

tensor([[0.5646, 0.9323, 0.4621],
        [0.4027, 0.1680, 0.1170],
        [0.5063, 0.6061, 0.5141]])

common image shape of [224, 224, 3] ([height, width, color_channels]).

In [124]:
random_image_size_tensor = torch.rand(size = (224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#Zeros and Ones

In [125]:
zeros = torch.zeros(size = (3,4))

In [126]:
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [127]:
ones = torch.ones(size = (3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

Creating a range and tensors like

In [128]:
zeros_to_ten_deprecated = torch.range(0, 10)

/tmp/ipython-input-3299064980.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zeros_to_ten_deprecated = torch.range(0, 10)


In [129]:
zeros_to_ten_deprecated

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [130]:
zeros_to_ten = torch.arange(start = 1, end = 10, step = 1)

In [131]:
zeros_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

one tensor of a certain type with the same shape as another tensor.

In [132]:
ten_zeros = torch.zeros_like(input= zeros_to_ten)

In [133]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

#Tensor datatypes



1.   32-bit Floating point  -->   torch.float32 or torch.float
2.   torch.cude  -->  Nvidia GPU



In [134]:
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype = None,
    device = None,
    requires_grad=False
)

In [135]:
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [136]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16



*   Shape - what shape is the tensor? (some operations require specific shape rules)

*   Dtype - what datatype are the elements within the tensor stored in?

*   Device - what device is the tensor stored on? (usually GPU or CPU)



In [137]:
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.7186, 0.8834, 0.2827, 0.5312],
        [0.5058, 0.0712, 0.1094, 0.4695],
        [0.2574, 0.9830, 0.6780, 0.1739]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


#Tensor operations

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [138]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [139]:
tensor * 10

tensor([10, 20, 30])

In [140]:
tensor

tensor([1, 2, 3])

In [141]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

#Matrix multiplication

In [142]:
import torch

In [143]:
tensor = torch.tensor([1,2,3])

In [144]:
tensor.shape

torch.Size([3])

In [145]:
tensor * tensor

tensor([1, 4, 9])

In [146]:
torch.matmul(tensor, tensor)

tensor(14)

In [147]:
# Can also use the "@" symbol for matrix multiplication, though not recommended

In [148]:
tensor @ tensor

tensor(14)

#One of the most common errors in deep learning (shape errors)

2 * 3 MATMUL 2 * 3

In [149]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

#torch.matmul(tensor_A, tensor_B) # (this will error)

#TRANSPOSE

In [150]:

print(tensor_B)

tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [151]:
tensor_B.T

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [152]:
tensor_A @ tensor_B.T

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [153]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


 torch.mm() is a short for torch.matmul()

In [154]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [155]:
tensor_C = torch.rand(3,6)

y= x . A^T +B

In [156]:
torch.manual_seed(42)
linear = torch.nn.Linear(6, 10)
x = tensor_C
output = linear(x)
print("input shape: ", x.shape)
print(f"\n output: \n {output} \n \n Output shape: {output.shape} ")

input shape:  torch.Size([3, 6])

 output: 
 tensor([[ 0.4519,  0.0039,  0.3547,  0.0671, -0.4688, -0.1042,  0.4596,  0.1179,
         -0.3384, -0.2384],
        [ 0.2870,  0.0331,  0.4936, -0.1333, -0.3913,  0.0635,  0.3168,  0.0239,
         -0.4897, -0.1309],
        [ 0.4011, -0.1783,  0.5252, -0.2483, -0.3290,  0.1261,  0.5011,  0.1319,
         -0.2497, -0.0488]], grad_fn=<AddmmBackward0>) 
 
 Output shape: torch.Size([3, 10]) 


Finding the mean, max, min, sum

In [157]:
x = torch.arange(0, 100, 10 )

In [158]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [159]:
x.min()

tensor(0)

In [160]:
x.max()

tensor(90)

In [161]:
x.type(torch.float32).mean()

tensor(45.)

#Positional min/max

You can also find the index of a tensor where the max or minimum occurs with torch.argmax() and torch.argmin() respectively.

In [162]:
tensor = torch.arange(0, 101, 10)

In [163]:
tensor

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [164]:
tensor.argmax()

tensor(10)

In [165]:
tensor.argmin()

tensor(0)

In [166]:
tensor =  torch.tensor([1, 99, 100, 77])

In [167]:
tensor.argsort()

tensor([0, 3, 1, 2])

#Change tensor datatype

If one tensor is in torch.float64 and another is in torch.float32, you might run into some errors.

But there's a fix.

You can change the datatypes of tensors using torch.Tensor.type(dtype=None) where the dtype parameter is the datatype you'd like to use.

In [168]:
tensor1 = torch.arange(10., 100., 10.)
tensor.dtype

torch.int64

In [169]:
tensor_float16 = tensor1.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [170]:
tensor_int8 = tensor1.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [171]:
new = tensor1 + tensor_int8.float()

In [172]:
print(new.argmax())

tensor(8)


#Reshaping, stacking, squeezing and unsqueezing

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

In [173]:
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [174]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [175]:
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [176]:
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [177]:
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [178]:
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [179]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


You can also rearrange the order of axes values with torch.permute(input, dims), where the input gets turned into a view with new dims.

In [180]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


#Indexing (selecting data from tensors)

Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

In [181]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [182]:
print(f"First square bracket:\n {x[0]}")

First square bracket:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [183]:
print(f"Second square bracket: {x[0][1]}")

Second square bracket: tensor([4, 5, 6])


In [184]:
print(f"Third square bracket: {x[0][1][2]}")

Third square bracket: 6


You can also use : to specify "all values in this dimension" and then use a comma (,) to add another dimension.

In [185]:
x[:, 0]

tensor([[1, 2, 3]])

In [186]:
x[:, 1]

tensor([[4, 5, 6]])

In [187]:
x[:, 2]

tensor([[7, 8, 9]])

In [188]:
x[0][1]

tensor([4, 5, 6])

Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension

In [189]:
x[:,:,1]

tensor([[2, 5, 8]])

In [190]:
x[:,:,2]

tensor([[3, 6, 9]])

In [191]:
x[:,0,:]

tensor([[1, 2, 3]])

#PyTorch tensors & NumPy

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

* torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.

* torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

In [196]:
import torch
import numpy as np
array1 = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array1)
array1, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

And if you want to go from PyTorch tensor to NumPy array, you can call tensor.numpy().

In [197]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [198]:
tensor = tensor + 1

#Reproducibility (trying to take the random out of random)

In [199]:
import torch

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(f"Tensor A \n {random_tensor_A}\n")
print(f"Tensor B \n {random_tensor_B}\n")

print(f"Does Tensor A equals to Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A 
 tensor([[0.5457, 0.7303, 0.5268, 0.6694],
        [0.3213, 0.4008, 0.2892, 0.9977],
        [0.6649, 0.5646, 0.9323, 0.4621]])

Tensor B 
 tensor([[0.4027, 0.1680, 0.1170, 0.5063],
        [0.6061, 0.5141, 0.1907, 0.0445],
        [0.5425, 0.9580, 0.9967, 0.6417]])

Does Tensor A equals to Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [204]:
import torch
import random

RANDOM_SEED = 42
torch.manual_seed(seed = RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed = RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(f"Tensor c: \n {random_tensor_C}")
print(f"Tensor D: \n {random_tensor_D}")

Tensor c: 
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Tensor D: 
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


In [205]:
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])